"""empty message

Revision ID: 20b4d518df5b
Revises: 3c89e95f03fc
Create Date: 2026-02-26 19:56:32.957571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b4d518df5b'
down_revision = '3c89e95f03fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_follower', sa.Integer(), nullable=False),
    sa.Column('id_followed', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_followed'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_follower'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
